export const ASSETS = {
  logo: "/images/logo.png",
  logoLogin: "/images/logo-login.png",
  logoLanding: "/images/logo-landing.png",
  logoComplete: "/images/logo-complete.png",
  arrowRight: "/images/arrow-right.svg",
  iconBell: "/images/icon-bell.svg",
  iconLocationPin: "/images/icon-location-pin.svg",
  iconShare: "/images/icon-share.svg",
  iconCalendarSmall: "/images/icon-calendar-small.svg",
  iconSearch: "/images/icon-search.svg",
  iconFilterReset: "/images/icon-filter-reset.svg",
  iconViewedCheck: "/images/icon-viewed-check.svg",
  iconAiSummary: "/images/icon-ai-summary.svg",
  iconRefresh: "/images/icon-refresh.svg",
  tabHome: "/images/tab-home.svg",
  tabJobs: "/images/tab-jobs.svg",
  tabLearning: "/images/tab-learning.svg",
  tabCalendar: "/images/tab-calendar.svg",
  tabMy: "/images/tab-my.svg",
} as const;
